# Generated by Django 2.1.2 on 2018-10-14 02:14

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField()),
                ('borrower', models.IntegerField()),
                ('title', models.CharField(max_length=48)),
                ('author', models.CharField(max_length=4096)),
                ('year', models.CharField(max_length=48)),
                ('status', models.CharField(choices=[('available', 'Available'), ('checked out', 'Checked Out')], default='available', max_length=48)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_borrowed', models.DateTimeField(blank=True, null=True)),
                ('pre_save_status', models.CharField(editable=False, max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=48, null=True)),
                ('email', models.CharField(max_length=48, null=True)),
                ('first_name', models.CharField(max_length=48, null=True)),
                ('last_name', models.CharField(max_length=48, null=True)),
                ('fb_id', models.CharField(max_length=48, null=True)),
                ('picture', models.URLField(max_length=300)),
                ('friends', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=48), null=True, size=None)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book_share_app.Profile'),
        ),
        migrations.AddField(
            model_name='book',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
    ]
