# Generated by Django 2.1.2 on 2018-10-15 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_share_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
