# Generated by Django 2.1.2 on 2018-10-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_share_app', '0002_auto_20181014_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrower',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.CharField(max_length=48, null=True),
        ),
    ]
