# Generated by Django 2.1.2 on 2018-10-16 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_share_app', '0003_auto_20181016_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='profile_id',
        ),
    ]
