# Generated by Django 2.1.2 on 2018-10-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_share_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
