# Generated by Django 2.1.2 on 2018-10-18 18:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_share_project', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('request', 'Request'), ('response', 'Response')], max_length=48)),
                ('status', models.CharField(max_length=48, null=True)),
                ('from_user', models.CharField(max_length=48, null=True)),
                ('to_user', models.CharField(max_length=48, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('book_id', models.CharField(max_length=48, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='requester',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='requests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('checked out', 'Checked Out'), ('requested', 'Requested')], default='available', max_length=48),
        ),
    ]
