# Generated by Django 2.1.2 on 2018-10-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_share_project', '0003_auto_20181018_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='requests',
        ),
    ]
