# Generated by Django 2.1.2 on 2018-10-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_share_project', '0004_auto_20181018_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='requester',
            field=models.CharField(max_length=48, null=True),
        ),
    ]
