# Generated by Django 2.1.2 on 2018-10-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_share_project', '0005_book_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(max_length=48, null=True),
        ),
    ]
