# Generated by Django 2.1.2 on 2018-10-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_share_project', '0006_auto_20181018_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrower',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='requester',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.URLField(max_length=1024),
        ),
    ]
